#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'encryption' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def encryption(s):
    # Write your code here
    s=s.replace(" ","")
    floor=math.floor(math.sqrt(len(s)))
    ceil=math.ceil(math.sqrt(len(s)))
    string =""
    for i in range(ceil):
        string+=(s[i::ceil])
        string+=" "
    return string    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = encryption(s)

    fptr.write(result + '\n')

    fptr.close()
